name: Create Stable Branch

on:
  workflow_dispatch:

jobs:
  createstable:
    name: Create stable branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Read version
        id: set-version
        run: |
          source ./config
          echo "version=$(echo ${VERSION})" >> $GITHUB_OUTPUT

      - name: Create stable branch
        run: git checkout -b stable-${{ steps.set-version.outputs.version }}

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com

      - name: Fix ARCHIVE_DATE
        run: |
          DATE=$(date -d 'yesterday' +%Y/%m/%d)
          sed -i 's@ARCHIVE_DATE.*@ARCHIVE_DATE=\"'"$DATE"'\"@g' config
          git add config
          git commit --message "Fixate ARCHIVE_DATE"

      # ❌ Usunięto: Set AUR-submodules

      - name: Push new branch
        run: git push origin stable-${{ steps.set-version.outputs.version }}

      - name: Increment version on master
        run: |
          source ./config
          NEXT=$((VERSION + 1))
          git checkout master
          sed -i 's@VERSION.*@VERSION=\"'"$NEXT"'\"@g' config
          git add config
          git commit --message "Bump version" --message "[skip ci]"
          git push
